/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package trabalhosd.telas;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author umestudantecristao
 */
public class JDialogAvaliarAlgoritmo extends javax.swing.JDialog {

    /**
     * Creates new form JDialogInserirDados
     */
    public JDialogAvaliarAlgoritmo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRespostaAlgoritmo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSelecionados = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListSintomas = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonEnviar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButtonCorreto = new javax.swing.JRadioButton();
        jRadioButtonErrado = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Treinar algoritmo");
        setResizable(false);

        jListSelecionados.setFont(new java.awt.Font("Fira Mono", 0, 12)); // NOI18N
        jListSelecionados.setFocusable(false);
        jListSelecionados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListSelecionadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListSelecionados);

        jLabel1.setFont(new java.awt.Font("Fira Sans Condensed", 0, 18)); // NOI18N
        jLabel1.setText("------------------SINTOMAS APRESENTADOS------------------");

        jListSintomas.setFont(new java.awt.Font("Fira Mono Medium", 0, 14)); // NOI18N
        jListSintomas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Febre", "Dor de cabeça", "Falta de ar", "Náusea", "Dor de barriga", "Nariz entupido", "Dor de ouvido", "Fraqueza", "Falta de apetite", "Diarréia" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListSintomas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListSintomasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListSintomas);

        jLabel2.setFont(new java.awt.Font("Fira Sans Condensed", 0, 18)); // NOI18N
        jLabel2.setText("------------------SELECIONE OS SINTOMAS------------------");

        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Fira Sans Condensed", 0, 14)); // NOI18N
        jLabel4.setText("Resposta do algoritmo:");

        jTextField1.setEditable(false);
        jTextField1.setFocusable(false);

        buttonGroupRespostaAlgoritmo.add(jRadioButtonCorreto);
        jRadioButtonCorreto.setText("Está correto");

        buttonGroupRespostaAlgoritmo.add(jRadioButtonErrado);
        jRadioButtonErrado.setText("Está errado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEnviar)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonCorreto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButtonErrado))
                                    .addComponent(jTextField1))))
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCorreto)
                    .addComponent(jRadioButtonErrado))
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEnviar)
                    .addComponent(jButtonCancelar))
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void adicionarEremoverLista(int index, JList<String> jlistEntrega, JList<String> jlistRecebe){
        DefaultListModel<String> modelEntrega = new DefaultListModel<String>();
        DefaultListModel<String> modelRecebe = new DefaultListModel<String>();

        String item = jlistEntrega.getModel().getElementAt(index);

        for (int i = 0; i < jlistEntrega.getModel().getSize(); i++) {
            if (jlistEntrega.getModel().getElementAt(i) != item) {
                modelEntrega.addElement(jListSintomas.getModel().getElementAt(i));
            }
        }

        jlistEntrega.setModel(modelEntrega);

        for (int i = 0; i < jlistRecebe.getModel().getSize(); i++) {
            modelRecebe.addElement(jlistRecebe.getModel().getElementAt(i));
        }

        modelRecebe.addElement(item);
        jlistRecebe.setModel(modelRecebe);
    }
    
    private void jListSintomasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListSintomasMouseClicked
        if (evt.getClickCount() == 2) {
            int index = jListSintomas.locationToIndex(evt.getPoint());
            if (index != -1) {
                adicionarEremoverLista(index, jListSintomas, jListSelecionados);
            }
        }
    }//GEN-LAST:event_jListSintomasMouseClicked

    private void jListSelecionadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListSelecionadosMouseClicked
         if (evt.getClickCount() == 2) {
            int index = jListSelecionados.locationToIndex(evt.getPoint());
            if (index != -1) {
                adicionarEremoverLista(index, jListSelecionados, jListSintomas);
            }
        
        }
    }//GEN-LAST:event_jListSelecionadosMouseClicked

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        ArrayList<String> listaSintomas = new ArrayList<String>();
        Object[] resposta = new Object[4];
        
        for (int i = 0; i < jListSelecionados.getModel().getSize(); i++) {
            listaSintomas.add(jListSelecionados.getModel().getElementAt(i));
        }
        
        int respostaAlgoritmo = -1;
        
        if(jRadioButtonCorreto.isSelected()){
            respostaAlgoritmo = 1;
        }
        
        resposta[0] = 1;
        resposta[1] = listaSintomas;
        resposta[2] = "Gripe";
        resposta[3] = respostaAlgoritmo;
        
        System.out.println("Tipo de requisição: " + resposta[0] + "\n" +
                           "Sintomas: " + resposta[1] + "\n" +
                           "Diagnóstico: " + resposta[2] + "\n" +
                           "'O algoritmo está correto?': " + resposta[3] + "\n"
                          );
        this.dispose();
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogAvaliarAlgoritmo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogAvaliarAlgoritmo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogAvaliarAlgoritmo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogAvaliarAlgoritmo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogAvaliarAlgoritmo dialog = new JDialogAvaliarAlgoritmo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupRespostaAlgoritmo;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jListSelecionados;
    private javax.swing.JList<String> jListSintomas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonCorreto;
    private javax.swing.JRadioButton jRadioButtonErrado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
